---
title: "Tarea clase 3"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    #number_sections: true
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSelenium)
library(tidyverse)

```

# Consigna: Descargar noticias de la página infobae de la sección España buscando "Deportivo Coruña campeón"
```{r}

rd <- rsDriver(browser = "firefox",
               chromever = NULL,
               port= 4455L)

remDr <- rd[["client"]]



remDr$navigate("https://www.infobae.com/")

remDr$maxWindowSize()

Sys.sleep(10)


remDr$findElements("id", "onesignal-slidedown-cancel-button")[[1]]$clickElement()

Sys.sleep(3)

xpath_boton_espania <- "//a[@href='https://www.infobae.com/espana/']"

boton_espania <- remDr$findElement(using = "xpath", value = xpath_boton_espania)

boton_espania$clickElement()

Sys.sleep(7)

remDr$findElements("id", "hamburger-icon")[[1]]$clickElement()

Sys.sleep(2)

remDr$findElements("id", "search-icon")[[1]]$clickElement()


Sys.sleep(2)

search_bar <- remDr$findElement(using = "id", value = "queryly_query")

Sys.sleep(2)

search_bar$sendKeysToElement(list("deportivo la coruña campeon"))

Sys.sleep(5)

remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")

Sys.sleep(5)

remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")

Sys.sleep(5)

# Función para desplazarse al final de la página
scroll_to_bottom <- function(driver, max_attempts = 10, delay = 4) {
  for (i in 1:max_attempts) {
    # Obtiene la altura actual de la página
    previous_height <- remDr$executeScript("return document.body.scrollHeight")
    
    # Se desplaza al final
    remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")
    
    # Esperar (parámetro de la función)
    Sys.sleep(delay)
    
    # Chequea si la altura cambió
    new_height <- remDr$executeScript("return document.body.scrollHeight")
    
    # Si la altura anterior de la página y la altura actual son igual, para.
    # También para luego de 10 intentos.
    if (new_height[[1]] == previous_height[[1]]) {
      message("Se alcanzó el final de la página.")
      break
    }
  }
}

# Llamar a la función para desplazarse al final de la página
scroll_to_bottom(remDr)

page_source <- remDr$getPageSource()[[1]]

Sys.sleep(3)

page <- read_html(page_source)


titles <- page %>% html_nodes("div.queryly_item_title") %>% 
  html_text() %>% 
  str_squish()

links <- page %>% 
  html_nodes("div.queryly_item_title") %>% 
  html_elements("a") %>% 
  html_attr("href") 

links <- links[!duplicated(links) ]

raiz <- "https://www.infobae.com"

links_completos <- str_c(raiz, links)


tabla_noticias <- function(links){
  
  
  noticia <- read_html(links)
  
  titulo <- noticia %>% 
    html_element("h1") %>% 
    html_text() %>% 
    str_squish()
  
  cuerpo <- noticia %>% 
    html_element("p.paragraph") %>% 
    html_text() %>% 
    str_squish()
  
  
  fecha  <- noticia %>% 
    html_element("span.sharebar-article-date") %>% 
    html_text() %>% 
    str_squish()
  
  autor  <- noticia %>% 
    html_element("span.author-name") %>% 
    html_text() %>% 
    str_squish()
  
  web <- links
  
  tabla_final <- as.data.frame(cbind("titulo"=titulo, "autor" = autor,  "cuerpo"=cuerpo,
                                     "fecha" = fecha, "Link" = web
  ))
  
  return(tabla_final)
  
}


noticias <- tibble(
  titulo=character(),
  cuerpo=character(),
  fecha=character(),
  autor= character()
)

print(paste("Se encontraron", length(links_completos), "noticias\n"))


for(i in 1:length(links_completos)){
  
  print(paste("Obteniendo información de noticia:\n ",links_completos[i]))
  
  resultado <- tabla_noticias(links_completos[i])
  
  noticias <- noticias %>% 
    bind_rows(resultado)
  
}

```