---
title: "Tarea clase 2 - R web scraping"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    #number_sections: true
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(rvest)
require(tidyverse)
require(here)
require(openxlsx)
```


# Consigna:

Scrapear todos los libros y su informaci칩n de un autor elegido en la p치gina: https://sigloxxieditores.com.ar/

Elijo al autor Karl Marx.
```{r}

pagina_marx <- read_html("https://sigloxxieditores.com.ar/?s=marx&post_type=product")


```

Selecciono un libro cualquiera e identifico los elementos:
-Titulo

-Autor

-Precio

-Biografia

Obtener titulo:
```{r}

pagina_libro <- read_html("https://sigloxxieditores.com.ar/libro/antologia/")

titulo <- pagina_libro %>% 
  html_element("h1.entry-title") %>% 
  html_text() %>% 
  str_squish()

```

Autor:
```{r}

autor <- pagina_libro %>% 
  html_element("a.author.main") %>% 
  html_text()

```

Precio:
```{r}

precio <- pagina_libro %>% 
  html_element("div.price") %>% 
  html_text() %>% 
  str_squish()

```


```{r}

bio <- pagina_libro %>% 
  html_elements("div.woocommerce-product-details__short-description") %>% 
  html_elements("p") %>% 
  html_text() %>% 
  str_squish()

```

Ahora que tenemos los elementos, buscamos todos los links en la p치gina.
```{r}

links <- pagina_marx %>% 
  html_elements("h3.wd-entities-title") %>% 
  html_elements("a") %>% 
  html_attr("href")

links
```

Creamos la funcion para scrapear:
```{r}

scrap_SXXI <- function(link){
  
  link <- read_html(link)
  
  titulo <- link %>% 
    html_element("h1.entry-title") %>% 
    html_text() %>% 
    str_squish()
  
  autor <- link %>% 
    html_element("a.author.main") %>% 
    html_text()
  
  precio <- link %>% 
    html_element("div.price") %>% 
    html_text() %>% 
    str_squish()
  
  
  bio <- link %>% 
    html_elements("div.woocommerce-product-details__short-description") %>% 
    html_elements("p") %>% 
    html_text2() %>% 
    str_squish() %>% 
    paste(collapse = " ") 
  
    tabla_final <- as.data.frame(cbind("titulo"=titulo, "autor" = autor, "Bio"=bio,  "precio"=precio))
  
  return(tabla_final)
  
}

  
```


```{r}

pagina_marx <- read_html("https://sigloxxieditores.com.ar/?s=marx&post_type=product")

obtiene_links <- pagina_marx %>% 
  html_elements("h3.wd-entities-title") %>% 
  html_elements("a") %>% 
  html_attr("href")

libros <- tibble(
                titulo=character(),
                Bio=character(),
                precio=character(),
                autor= character()
                )

for(i in 1:length(obtiene_links)){
  
  print(paste("Se encontraron",length(obtiene_links), "libros" ))
  print(paste("Obteniendo informaci칩n de libro: ", i))
  
  resultado <- scrap_SXXI(obtiene_links[i])

  libros <- libros %>% 
    bind_rows(resultado)
  
}


print(libros)


```

Guardamos tabla.
```{r}

writexl::write_xlsx(libros, "tabla_libros.xlsx")

```

